dataset_name: 'clio'

ros_topics:
  rgb: "/dominic/forward/color/image_raw"
  depth: "/dominic/forward/depth/image_rect_raw"
  odom: "/dominic/forward/colmap_odom"

intrinsic:
  fx: 372.4634094238281
  fy: 371.5072021484375
  cx: 315.9902073557914
  cy: 254.59437002701452