# low mobility examples
lm_examples:
  - "building"
  - "apartment"
  - "window"
  - "door"
  - "balcony"
  - "street"
  - "sidewalk"
  - "crosswalk"
  - "fence"
  - "shop"
  - "restaurant"
  - "cafe"
  - "stairs"
  - "gate"
  - "signboard"
  - "billboard"
  - "road-marking"
  - "awning"
  - "scaffold"

# high mobility examples
hm_examples:
  - "car"
  - "truck"
  - "bicycle"
  - "motorcycle"
  - "traffic-cone"
  - "traffic-barrier"
  - "trash-bin"
  - "mailbox"
  - "bench"
  - "flowerpot"
  - "tree"
  - "bush"
  - "construction-sign"
  - "traffic-sign"
  - "streetlight"
  - "traffic-light"
  - "fire-hydrant"
  - "person"

# Extra descriptions for low mobility examples
lm_descriptions:
  - "fixed urban structures and buildings"
  - "architectural elements that rarely move"
  - "infrastructure forming the static environment"
  - "elements permanently attached to ground or walls"

