defaults:
  - _self_
#  - override hydra/job_logging: stdout

hydra:
  run:
    dir: outputs
  output_subdir: null

# scene config
terrain: "carla"  # see assets/terrains/usd_scene.py

# agent controll config
controller: "keyboard"  # keyboard / goal_point

# locomotion config
policy: eilab  # (reconstructed from legged-loco)
observation_len: 5
policy_device: cuda:0

# ui config
sim_app:
  headless: False
  record_video: False
  anti_aliasing: 0
  width: 1280
  height: 720
  hide_ui: False