defaults:
  - _self_2.0
#  - override hydra/job_logging: stdout

# scene config
terrain: "blender"   # see assets/terrains/usd_scene.py
add_physics: True # if the terrain usd dont have collision

# locomotion config
policy: eilab  # (reconstructed from legged-loco)
policy_name: "policy_roughRecover_dt01.jit"
observation_len: 5
policy_device: cuda:0

# camera config
publish_dt: 0.1
sensors:
  camera:
    width: 640
    height: 480
    fx: 320.0
    fy: 320.0
    cx: 320.0
    cy: 240.0
monitor_camera: False
camera_follow: False

# ui config
sim_app:
  headless: False
  record_video: True  # if record_video=True, should set enable_cameras=True in simulation_app
  anti_aliasing: 0
  width: 1280
  height: 720
  hide_ui: False