defaults:
  - _self_
#  - override hydra/job_logging: stdout

# scene config
terrain: "carla"   # see assets/terrains/usd_scene.py
add_physics: False # if the terrain usd dont have collision

# agent controll config
controller: "keyboard"  # keyboard / goal_point

# locomotion config
policy: eilab  # (reconstructed from legged-loco)
observation_len: 5
policy_device: cuda:0

sensors:
  camera:
    width: 640
    height: 480
    fx: 320.0
    fy: 320.0
    cx: 320.0
    cy: 240.0

# ui config
sim_app:
  headless: False
  record_video: True  # if record_video=True, should set enable_cameras=True in simulation_app
  anti_aliasing: 0
  width: 1280
  height: 720
  hide_ui: False