# ============================================================
# CAMERA CONFIG
# ============================================================
intrinsic:
  fx: 320
  fy: 320
  cx: 320
  cy: 240
# extrinsics:
#   [1, 0, 0, 0, 
#   0, 1, 0, 0, 
#   0, 0, 1, 0,
#   0, 0, 0, 1]

# ============================================================
# SCENARIO CONFIG
# ============================================================
# dataset_name: 'road'
# dataset_name: 'warehouse'
# dataset_name: 'house'
dataset_name: 'garden'

# ============================================================
# OUTPUT CONFIG
# ============================================================
output_path: ../../outputs

# ============================================================
# LOGGING CONFIG
# ============================================================
logging_config: ./config/logging_config.yaml