# ============================================================
# ROBOT CONFIG
# ============================================================
# Robot radius, for collision detection in path planning
robot_radius: 0.5

# ============================================================
# SCENARIO CONFIG
# ============================================================
# dataset_name: 'road'
# dataset_name: 'warehouse'
# dataset_name: 'house'
# dataset_name: 'garden'
# dataset_name: 'factory'
dataset_name: 'city'
# dataset_name: 'supermarket'

# ============================================================
# OUTPUT CONFIG
# ============================================================
output_path: ../../outputs

# ============================================================
# LOGGING CONFIG
# ============================================================
logging_config: ./config/logging_config.yaml