# ============================================================
# CAMERA CONFIG
# ============================================================
intrinsic:
  fx: 320
  fy: 320
  cx: 320
  cy: 240
# extrinsics:
#   [1, 0, 0, 0, 
#   0, 1, 0, 0, 
#   0, 0, 1, 0,
#   0, 0, 0, 1]

# ============================================================
# ONLINE ROS CONFIG
# ============================================================
dataset_name: 'road'

# ============================================================
# OUTPUT CONFIG
# ============================================================
# output directory
output_path: ./outputs

# ============================================================
# LOGGING CONFIG
# ============================================================
# logging config
logging_config: ./config/support_config/logging_config.yaml