# ============================================================
# SCENARIO CONFIGURATION
# ============================================================
# dataset_name: 'road'
dataset_name: 'warehouse'
# dataset_name: 'house'
# dataset_name: 'garden'
# dataset_name: 'factory'
# dataset_name: 'city'
# dataset_name: 'supermarket'

# ============================================================
# SCENARIO CONFIGURATION
# ============================================================
dataset_name: 'field'

# ============================================================
# RANGE SENSOR CONFIG
# ============================================================
range_sensor: "depth"

# ============================================================
# CAMERA CONFIG
# ============================================================
intrinsics:
  fx: 320
  fy: 320
  cx: 320
  cy: 240
# odom frame -> camera frame, here use /odom_camera
extrinsics:
  - [1, 0, 0, 0.0]
  - [0, 1, 0, 0.0]
  - [0, 0, 1, 0.0]
  - [0, 0, 0, 1.0]

# ============================================================
# SemMap COnfig
# ============================================================
resolution: 0.05
boundary: True
sem_width: 20.0
sem_height: 20.0

# ============================================================
# PCD CONFIG
# ============================================================
layout_voxel_size: 0.1
layout_update_radius: 10.0
occ_update_radius: 5.0
occ_thr: 2

# small mask filtering threshold
small_mask_th: 50

# minimum points threshold for object's PCD
min_points_threshold: 5

# pcd params
downsample_voxel_size: 0.05
dbscan_remove_noise: True
dbscan_eps: 0.1
dbscan_min_points: 15
pcd_sample_ratio: 0.1

