# ============================================================
# ROBOT CONFIGURATION
# ============================================================
# Robot radius, for collision detection in path planning
robot_radius: 0.4

# ============================================================
# PRELOADING CONFIGURATION
# ============================================================
preload_path: "map" # 拼接后的完整路径是 "./output/${dataset_name}/map"

# ============================================================
# OUTPUT CONFIGURATION
# ============================================================
output_path: ../../outputs

# ============================================================
# LOGGING CONFIGURATION
# ============================================================
logging_config: ./config/logging_config.yaml

# ============================================================
# MODEL CONFIGURATION
# ============================================================
yolo:
  model_path: model/yolov8l-worldv2.pt

  # List of background classes
  bg_classes: ["wall", "floor", "ceiling"]
  skip_bg: False

  # Whether to use a predefined class list
  use_given_classes: True

  ## The given classes lists
  given_classes_path: ./class_list

  # Pre-set for stable filter, do not delete this
  num_classes: 0

sam:
  # model_path: model/sam_l.pt
  model_path: model/mobile_sam.pt

fastsam:
  model_path: model/FastSAM-s.pt

clip:
  model_path: model
  # model_name: ViT-H-14
  # pretrained: laion2b_s32b_b79k
  # mobile clip V1
  # model_name:  MobileCLIP-S2
  # pretrained: datacompdr
  # mobile clip V2
  model_name:  MobileCLIP2-S2
  pretrained: dfndr2b
  clip_length: 512
  # clip_length: 1024

device: cuda

# ============================================================
# DUALMAP VISUALIZATION CONFIGURATION
# ============================================================
### VISUALIZATION CONFIG
use_rerun: False

# ============================================================
# DUALMAP DETECTER CONFIGURATION
# ============================================================
# Enable object detection during mapping
run_detection: True
# Save detection results to disk
save_detection: False
# detection saving and loading directory
# detection_path: ${output_path}/${dataset_name}_${scene_id}/detections
detection_path: detections
# Generate yolo detection rgb image
generate_detection: True
# Show overlapping 3D bounding boxes on Rerun (slower performance)
show_3d_bbox_overlapped: False

## FastSAM Settings
# Use FastSAM for Open-Voca supplementation
use_fastsam: false
fastsam_confidence: 0.80
# Display FastSAM debug outputs on Rerun
show_fastsam_debug: False

## Detection Refinement
# skip refinement will be faster but less accurate
skip_refinement: False

## Feature Settings
# Use Text and Image weighted feats for object feature
# text_weight = 1 - image_weight
use_weighted_feature: True
image_weight: 0.7
# Use average feat for unknown classes detected by FastSAM
use_avg_feat_for_unknown: True

# ============================================================
# DUALMAP MATCHING CONFIGURATION
# ============================================================
### MATCHING CONFIG
# similarity threshold for matching
sim_threshold: 1.0

# ============================================================
# DUALMAP KEYFRAME CONFIGURATION
# ============================================================
### KEYFRAME CONFIG
time_threshold: 1.5
pose_threshold: 0.5
rotation_threshold: 5

# ============================================================
# DUALMAP LOCAL OBJECTS CONFIGURATION (CONCRETE OBJECTS)
# ============================================================
### LOCAL OBJECTS CONFIG --> CONCRETE OBJECTS
active_window_size: 10
downsample_interval: 1
# Param for Split Detection
max_common_th: 6
max_pending_count: 5
# Param for Stability Check
stable_num: 3

# ============================================================
# SYSTEM MAPPING CONFIGURATION
# ============================================================
### GENERAL MAP CONFIG
# If True, run local mapping only and get local map
# If False, run both local and global mapping and get global map
run_local_mapping_only: False
# Post 3D-level merging between objects, just like ConceptGraphs and HOV-SG
# If True, the system will merge the local objects with similarity.
merge_local_map: False
merge_sim_threshold: 0.9

# Map objects saving directory, if save map
map_save_path: map  # 拼接后的完整路径是 ./outputs/${dataset_name}/map
# Save the generated local map
save_local_map: True
# Save the global map (set False if run_local_mapping_only is True)
save_global_map: True

# DEBUG: save cropped images for every object
save_cropped: False

### LAYOUT CONFIG
save_layout: True

# ============================================================
# PATH PLANNING CONFIGURATION
# ============================================================
# Path planning interval (seconds)
path_planning_interval: 3.0

# Editing wall if the wall generation result is not good
edit_wall: False

# ============================================================
# MOBILITY CONFIGURATION
# ============================================================
check_mobility: false

# low mobility examples
lm_examples: []

# high mobility examples
hm_examples: []

# Extra descriptions for low mobility examples
lm_descriptions:
  - "urban structures, infrastructures, and objects fixed to the ground"
  - "architectural and environmental components that rarely move"
  - "elements forming the static and stable part of the city scene"
  - "man-made or natural objects that remain stationary for long periods"
