# ============================================================
# RANGE SENSOR CONFIG
# ============================================================
range_sensor: "lidar"

lidar_extrinsics:
  - [0, -1, 0, 0]
  - [0, 0, -1, 0]
  - [1, 0, 0, 0]
  - [0, 0, 0, 1]

# ============================================================
# SemMap Config
# ============================================================
resolution: 0.05
boundary: True
sem_width: 30.0
sem_height: 30.0

# ============================================================
# PCD CONFIG
# ============================================================
layout_voxel_size: 0.1
layout_update_radius: 20.0
occ_update_radius: 8.0
occ_thr: 1

# small mask filtering threshold
small_mask_th: 6

# minimum points threshold for object's PCD
min_points_threshold: 3

# pcd params
downsample_voxel_size: 0.05
dbscan_remove_noise: True
dbscan_eps: 0.2
dbscan_min_points: 3
pcd_sample_ratio: 1.0
