# ============================================================
# SCENARIO CONFIGURATION
# ============================================================
dataset_name: 'city'

# ============================================================
# RANGE SENSOR CONFIG
# ============================================================
range_sensor: "lidar"

lidar_extrinsics:
  - [0, -1, 0, 0]
  - [0, 0, -1, -0.1]
  - [1, 0, 0, -0.3]
  - [0, 0, 0, 1]

# ============================================================
# CAMERA CONFIG
# ============================================================
intrinsics:
  fx: 320
  fy: 320
  cx: 320
  cy: 240
  # dist(optional): [k1, k2, p1, p2, k3]

# odom frame -> camera frame, here use /odom_lidar (lidar_extrinsics.inv)
extrinsics:
  - [ 0,  0,  1,  0.3 ]
  - [-1,  0,  0,  0.0 ]
  - [ 0, -1,  0, -0.1 ]
  - [ 0,  0,  0,  1.0 ]

# ============================================================
# Controller Config
# ============================================================
controller:
  kp_ang: 0.6
  kp_lin: 0.6
  min_lin_vel: 0.6
  max_lin_vel: 2.0
  max_ang_vel: 1.0
  yaw_error_threshold: 0.8

# ============================================================
# SemMap Config
# ============================================================
resolution: 0.05
boundary: True
sem_width: 30.0
sem_height: 30.0

# ============================================================
# PCD CONFIG
# ============================================================
layout_voxel_size: 0.1
layout_update_radius: 20.0
occ_update_radius: 8.0
occ_thr: 1

# small mask filtering threshold
small_mask_th: 6

# minimum points threshold for object's PCD
min_points_threshold: 3

# pcd params
downsample_voxel_size: 0.05
dbscan_remove_noise: True
dbscan_eps: 0.2
dbscan_min_points: 3
pcd_sample_ratio: 1.0
