# ============================================================
# RANGE SENSOR CONFIG
# ============================================================
range_sensor: "lidar"  

lidar_extrinsics:
  - [0, -1, 0, 0]
  - [0, 0, -1, 0]
  - [1, 0, 0, 0]
  - [0, 0, 0, 1]

# ============================================================
# PCD CONFIG
# ============================================================
layout_voxel_size: 0.1
layout_update_radius: 10.0

# small mask filtering threshold
small_mask_th: 6

# minimum points threshold for object's PCD
min_points_threshold: 3

# pcd params
downsample_voxel_size: 0.05
dbscan_remove_noise: False
dbscan_eps: 0.1
dbscan_min_points: 10
pcd_sample_ratio: 1.0
