check_mobility: false

# low mobility examples
lm_examples: []

# high mobility examples
hm_examples: []

# Extra descriptions for low mobility examples
lm_descriptions:
  - "urban structures, infrastructures, and objects fixed to the ground"
  - "architectural and environmental components that rarely move"
  - "elements forming the static and stable part of the city scene"
  - "man-made or natural objects that remain stationary for long periods"

