defaults:
  - base_config
  - system_config
  - support_config/mobility_config@_here_
  - _self_

# ============================================================
# CAMERA CONFIG
# ============================================================
intrinsic:
  fx: 320
  fy: 320
  cx: 320
  cy: 240
# extrinsics:
#   [1, 0, 0, 0, 
#   0, 1, 0, 0, 
#   0, 0, 1, 0,
#   0, 0, 0, 1]

# ============================================================
# ROS CONFIG
# ============================================================
# Topic names
ros_topics:
  rgb: "/camera/rgb/image_raw"
  depth: "/camera/depth/image_raw"
  odom: "/camera/pose"
  camera_info: "/camera_info"
  
# Frequency of the main ROS loop (Hz)
# Controls how many times per second spin() calls run_once()
ros_rate: 15

# If RGB & Depth topics are published as compressed image topics, set to true
# If false, topics are expected to be raw image topics
use_compressed_topic: false

# Maximum allowed time difference (in seconds) between synchronized topics
sync_threshold: 0.1


# ============================================================
# DUALMAP CONFIG
# ============================================================
## Detection Config
# Enable object detection during mapping
run_detection: True

# Show detection results on Rerun during runtime
visualize_detection: True

# Use FastSAM for Open-Voca supplementation
use_fastsam: False

# Detection Refinement
# skip refinement will be faster but less accurate
skip_refinement: false

## Visualization
# Enable Rerun visualization
use_rerun: true
# Enable Rviz visualization
use_rviz: false

## Parallelization
# Use parallel processing (False = sequential)
use_parallel: true

### END PROCESS CONFIG
# if True, the system save the map objects, calculate the time cost, and end the process safely
# In ROS mode, this will trigger the end of the system if no new data input for a while
use_end_process: true


# ============================================================
# SYSTEM MAPPING CONFIG
# ============================================================
# If True, run local mapping only and get local map
# If False, run both local and global mapping and get global map
run_local_mapping_only: false

# Save the generated local map
save_local_map: true

# Save the global map (set False if run_local_mapping_only is True)
save_global_map: true


# ============================================================
# PRELOADING CONFIG
# ============================================================
# Preload an existing global map from disk
preload_global_map: false

# Preload an existing layout pcd and wall pcd from disk
# If preload the layout, the layout pcd thread will be disabled
preload_layout: false

# Path to preload map data.
# If empty, the system will use the default preload path
preload_path: "map"   # would be f'{output_path}/{dataset_name}/{preload_path}'
# preload_path: "dataset/HM3D_collect/00829-QaLdnwvtxbs/global_map/hm3d"
# preload_path: "output/map_results/replica_room_0/map"

# Preload action paths for visualization
use_given_path: false
given_path_dir: ""