defaults:
  - base_config
  - rerun_config@_here_
  - _self_

# ============================================================
# MODEL CONFIG
# ============================================================
yolo:
  _target_: _self_
  model_path: model/yolov8m-worldv2.pt

  # List of background classes
  bg_classes: ["wall", "floor", "ceiling"]
  skip_bg: False

  # Whether to use a predefined class list (True = use given list, False = use ground truth classes)
  # Default is True
  use_given_classes: True

  ## The given classes lists
  given_classes_path: ./config/class_list

  # Pre-set for stable filter, do not delete this
  num_classes: 0

sam:
  _target_: _self_
  # model_path: model/sam_l.pt
  model_path: model/mobile_sam.pt

fastsam:
  _target_: _self_
  model_path: model/FastSAM-s.pt

clip:
  _target_: _self_
  model_name:  MobileCLIP-S2
  # model_name: ViT-H-14
  pretrained: datacompdr
  # pretrained: laion2b_s32b_b79k
  clip_length: 512
  # clip_length: 1024

device: cuda

# ============================================================
# DUALMAP CONFIG
# ============================================================
### VISUALIZATION CONFIG
use_rerun: False

### OBSERVATION GENERATION CONFIG
## General Detection Settings
# Enable object detection during mapping
run_detection: True
# Save detection results to disk
save_detection: False
# detection saving and loading directory
# detection_path: ${output_path}/${dataset_name}_${scene_id}/detections
detection_path: detections
# Generate yolo detection rgb image
generate_detection: True
# Show overlapping 3D bounding boxes on Rerun (slower performance)
show_3d_bbox_overlapped: False

## FastSAM Settings
# Use FastSAM for Open-Voca supplementation
use_fastsam: false
fastsam_confidence: 0.80
# Display FastSAM debug outputs on Rerun
show_fastsam_debug: False

## Detection Refinement
# skip refinement will be faster but less accurate
skip_refinement: False
# small mask filtering threshold
small_mask_th: 50

## Feature Settings
# Use Text and Image weighted feats for object feature
# text_weight = 1 - image_weight
use_weighted_feature: True
image_weight: 0.7
# Use average feat for unknown classes detected by FastSAM
use_avg_feat_for_unknown: True

## PCD Settings
# minimum points threshold for object's PCD
min_points_threshold: 5
# pcd params
downsample_voxel_size: 0.05
dbscan_remove_noise: !!bool True
dbscan_eps: 0.1
dbscan_min_points: 10
pcd_sample_ratio: 0.1

### MATCHING CONFIG
# similarity threshold for matching
sim_threshold: 1.0

### KEYFRAME CONFIG
time_threshold: 1.5 # set 1.5 because the view average detections are ~10, local mapping time would be ~1.0s per frame
pose_threshold: 0.5
rotation_threshold: 5

### LOCAL OBJECTS CONFIG --> CONCRETE OBJECTS
active_window_size: 10
downsample_interval: 1
# Param for Split Detection
max_common_th: 6
max_pending_count: 5
# Param for Stability Check
stable_num: 3

### GLOBAL OBJECTS CONFIG --> ANCHOR OBJECTS
# if True, the global(abstract) map will no update
no_update: False

### END PROCESS CONFIG
# if True, the system save the map objects, calculate the time cost, and end the process safely
# In ROS mode, this will trigger the end of the system if no new data input for a while
use_end_process: True

### PARALLELIZATION
# Use parallel processing (False = sequential)
use_parallel: True

### SHOW: Resolution of NavigationGraph in [GlobalManager, LocalManager, show_semantic_map]
resolution: 0.03

# ============================================================
# SYSTEM MAPPING CONFIG
# ============================================================
### GENERAL MAP CONFIG
# If True, run local mapping only and get local map
# If False, run both local and global mapping and get global map
run_local_mapping_only: False
# Post 3D-level merging between objects, just like ConceptGraphs and HOV-SG
# If True, the system will merge the local objects with similarity.
merge_local_map: False
merge_sim_threshold: 0.9

# Map objects saving directory, if save map
map_save_path: map  # 拼接后的完整路径是 ./outputs/${dataset_name}/map
# Save the generated local map
save_local_map: True
# Save the global map (set False if run_local_mapping_only is True)
save_global_map: True

# DEBUG: save cropped images for every object
save_cropped: False

### LAYOUT CONFIG
layout_voxel_size: 0.05 
save_layout: True
layout_update_radius: 10.0  # m

# ============================================================
# PRELOADING CONFIG
# ============================================================
# Path to preload map data.
preload_path: "map" # 拼接后的完整路径是 "./output/${dataset_name}/map"

# Preload action paths for visualization
use_given_path: False
given_path_dir: ""

# ============================================================
# PATH PLANNING CONFIG
# ============================================================
# Path planning interval (seconds)
path_planning_interval: 10.0

# Editing wall if the wall generation result is not good
edit_wall: False
save_wall: False