version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    mode: w # write not attach
    filename: 'default.log'

root:
  level: INFO
  handlers: [console, file]