dataset_name: 'self_collected'
camera_params:
  image_height: 680
  image_width: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 1000.0 #for depth image in png format
  crop_edge: 0