# dataset_name: 'self_collected'

ros_topics:
  rgb: "/camera/rgb/image_raw"
  depth: "/camera/depth/image_raw"
  odom: "/camera/pose"
  camera_info: "/camera_info"

intrinsic:
  fx: 640
  fy: 640
  cx: 320
  cy: 240